CREATE DATABASE LIBRARYDB;
USE LIBRARYDB;
CREATE TABLE BOOKS (
    BOOK_ID INT AUTO_INCREMENT PRIMERY KEY,
    TITLE VARCHAR(100),
    AUTHOR VARCHAR(100),
    PRICE DECIMAL(10,2),
    IS_AVAILABLE BOOLEAN
);

INSERT INTO BOOKS(TITLE ,AUTHOR, PRICE,IS_AVAILABLE) VALUES 
('ATOMIC HABITS','JAMES CLEAR',450.00,TRUE),
('THE ALCHEMIST','PAULO COELHO',300.00, TRUE),
('DEEP WORK','CAL NEWPORT',550.00,FALSE);

UPDATE BOOKS SET PRICE =500.00 WHERE BOOK_ID =2;

DELETE FROM BOOKS WHERE IS_AVAILABLE =FALSE;
