CREATE DATABASE TRAININGDB ;
USE TRAININGDB;
CREATE TABLE STUDENTS (
    USER_ID INT AUTO_INCREMENT PRIMERY KEY,
    FULL_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    IS_ACTIVE BOOLEAN
);



INSERT INTO STUDENTS(FULL_NAME,EMAIL,IS_ACTIVE) VALUES
('ISHWARI PATIL','ISHWARI@GMAIL.COM',TRUE),
('SNEHAL POTE','SNEHAL@GMAIL.COM',FALSE);

TRUNCATE TABLE STUDENTS;

DROP TABLE STUDENTS;
