CREATE DATABASE SCHOOLDB;
USE SCHOOLDB;
CREATE TABLE STUDENTS(
    STUDENT_ID INT AUTO_INCREMENT PRIMERY KEY,
    NAME VARCHAR(100),
    CLASS VARCHAR(50)
);

CREATE TABLE MARKS (
    MARK_ID INT AUTO_INCREMENT PRIMERY KEY,
    STUDENT_ID INT,
    SUBJECT VARCHAR(50),
    MARKS INT
);

INSERT INTO STUDENTS(NAME, CLASS) VALUES
('ISHWARI','10A'),
('SMEHAL','10B'),
('SAEE','10A');

INSERT INTO MARKS (STUDENT_ID ,SUBJECT,MARKS) VALUES
(1,'MATH',85),
(2,'SCIENCE',90),
(1,'ENGLISH',78);

SELECT * FROM STUDENTS CROSS JOIN MARKS;

SELECT STUDENTS.NAME, MARKS.SUBJECT ,MARKS.MARKS
FROM STUDENTS
INNER JOIN MARKS ON STUDENTS.STUDENT_ID = MARKS.STUDENT_ID;


SELECT STUDENTS.NAME , MARKS.SUBJECT, MARKS.MARKS
FROM STUDENTS 
LEFT JOIN MARKS ON STUDENTS.STUDENT_ID =MARKS.STUDENT_ID;



