CREATE DATABASE INDEXDB;
USE INDEXDB;
CREATE TABLE PRODUCTS (
  PRODUCT_ID INT PRIMARY KEY,
  PRODUCT_NAME VARCHAR(100),
  CATEGORY VARCHAR(50),
  PRICE DECIMAL(10,2)
);


INSERT INTO PRODUCTS (PRODUCT_ID ,PRODUCT_NAME, CATEGORY,PRICE) VALUES
(1,'LAPTOP','ELECTRONIC',55000.00),
(2,'CHAIR','FURNITURE',3000.00),
(3,'MOBILE','ELECTRONIC',22000.00);

CREATE INDEX IDX_PRODUCT_NAME ON
PRODUCTS(PRODUCT_NAME) ;

  CREATE  UNIQUE INDEX IDX_UNIQUE_CATEGORY ON
  PRODUCTS (CATEGORY) ;

  DROP INDEX IDX_PRODUCT_NAME ON PRODUCTS;

