CREATE DATABASE EMPLOYEEDB;
USE EMPLOYEEDB;
CREATE TABLE EMPLOYEES(
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(100),
    SALARY DECIMAL(10,2)
);


INSERT INTO EMPLOYEES (EMP_ID,EMP_NAME,SALARY) VALUES
(1,'ISHWARI',10000.00),
(2,'PIUU',50000.00),
(3,'ANUU',900000.00);

SELECT* FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;