CREATE DATABASE MYDB;
USE MYDB;
CREATE TABLE INFOS (
  ROLL_NO INT,
  NAME VARCHAR(100),
  ADDRESS VARCHAR(100)

);


INSERT INTO INFOS(ROLL_NO ,NAME ,ADDRESS) VALUES 
(1,'YASH','PUNE'),
(2,'OM','VANI'),
(3,'RIDDHU','MUMBAI');
SELECT * FROM INFOS WHERE NAME ='OM';

EXPLAIN SELECT * FROM INFOS WHERE NAME ='OM';

SHOW PROCESSLIST;
 
